from classes import Character, Scene, Node, Evidence, CourtRecord, Option

WAITING_ROOM_BG = "backgrounds/waiting-room.jpg"
DEFENSE_SIDE_BG = "backgrounds/defense-side.jpg"
PROSECUTOR_SIDE_BG = "backgrounds/prosecutor-side.jpg"
WITNESS_SIDE_BG = "backgrounds/witness-side.jpg"
JUDGE_SIDE_BG = "backgrounds/judge-side.jpg"
ASSISTANT_SIDE_BG = "backgrounds/defense-assistant-side.jpg"

characters = [
    Character(name="Léna", age=22, description="L'accusée dans l'affaire. Elle aurait été vu avec l'arme du crime dans les mains quelques temps avant le meurtre.", photo="characters/lena/profile.png", sprites={
        "angry": "characters/lena/angry.gif",
        "angry-talking": "characters/lena/angry-talking.gif",
        "backside": "characters/lena/backside.gif",
        "normal": "characters/lena/normal.gif",
        "normal-talking": "characters/lena/normal-talking.gif",
        "sad": "characters/lena/sad.gif",
        "sad-talking": "characters/lena/sad-talking.gif",
        "surprised": "characters/lena/surprised.gif",
        "surprised-talking": "characters/lena/surprised-talking.gif",
        "thinking": "characters/lena/thinking.gif",
        "thinking-talking": "characters/lena/thinking-talking.gif",
        "smiling": "characters/lena/smiling.gif",
        "smiling-talking": "characters/lena/smiling-talking.gif",
        "slam": "characters/lena/slam.gif",
        "slam-talking": "characters/lena/slam-talking.gif",
        "turn": "characters/lena/turn.gif",
    }),
    Character(name="Marie-Claire", age=45, description="La procureure de l'affaire. Elle est à l'affut de la moindre signature manquante sur les feuilles de présence.", photo="characters/marie-claire/profile.png", sprites={
        "damaged": "characters/marie-claire/damaged.gif",
        "no-finger": "characters/marie-claire/no-finger.gif",
        "no-finger-talking": "characters/marie-claire/no-finger-talking.gif",
        "normal": "characters/marie-claire/normal.gif",
        "normal-talking": "characters/marie-claire/normal-talking.gif",
        "overhead": "characters/marie-claire/overhead.gif",
        "overhead-talking": "characters/marie-claire/overhead-talking.gif",
        "stern": "characters/marie-claire/stern.gif",
        "stern-talking": "characters/marie-claire/stern-talking.gif",
        "sweating": "characters/marie-claire/sweating.gif",
        "sweating-talking": "characters/marie-claire/sweating-talking.gif",
        "whipping": "characters/marie-claire/whipping.gif",
    }),
    Character(name="Elouan", age=22, description="L'avocat de la défense.", photo="characters/elouan/profile.png", sprites={
        "confident": "characters/elouan/confident.gif",
        "confident-talking": "characters/elouan/confident-talking.gif",
        "normal": "characters/elouan/normal.gif",
        "normal-talking": "characters/elouan/normal-talking.gif",
        "thinking": "characters/elouan/thinking.gif",
        "thinking-talking": "characters/elouan/thinking-talking.gif",
        "determined": "characters/elouan/determined.gif",
        "determined-talking": "characters/elouan/determined-talking.gif",
        "dismayed": "characters/elouan/dismayed.gif",
        "dismayed-talking": "characters/elouan/dismayed-talking.gif",
        "pointing": "characters/elouan/pointing.gif",
        "pointing-talking": "characters/elouan/pointing-talking.gif",
        "shaking-head": "characters/elouan/shaking-head.gif",
        "shocked": "characters/elouan/shocked.gif",
        "slamming-desk": "characters/elouan/slamming-desk.gif",
    }),
    Character(name="Venceslas", age=50, description="Le juge de l'affaire. Apparemment il a hâte de rendre son verdict pour aller à Perrault (l'apéro).", photo="characters/juge/profile.png", sprites={
        "nodding-head": "characters/juge/nodding-head.gif",
        "normal": "characters/juge/normal.gif",
        "normal-talking": "characters/juge/normal-talking.gif",
        "stern": "characters/juge/stern.gif",
        "stern-talking": "characters/juge/stern-talking.gif",
        "thinking": "characters/juge/thinking.gif",
        "surprised": "characters/juge/surprised.gif",
        "surprised-talking": "characters/juge/surprised-talking.gif",
        "shaking-head": "characters/juge/shaking-head.gif",
    }),
    Character(name="Romane", age=24, description="La détective et assistante de l'avocat.", photo="characters/mia/profile.png", sprites={
        "grinning": "characters/mia/grinning.gif",
        "grinning-talking": "characters/mia/grinning-talking.gif",
        "normal": "characters/mia/normal.gif",
        "normal-talking": "characters/mia/normal-talking.gif",
        "smiling": "characters/mia/smiling.gif",
        "smiling-talking": "characters/mia/smiling-talking.gif",
        "surprised": "characters/mia/surprised.gif",
        "surprised-talking": "characters/mia/surprised-talking.gif",
        "exasperated": "characters/mia/exasperated.gif",
        "exasperated-talking": "characters/mia/exasperated-talking.gif",
        "sad": "characters/mia/sad.gif",
        "sad-talking": "characters/mia/sad-talking.gif",
        "shocked": "characters/mia/shocked.gif",
        "shocked-talking": "characters/mia/shocked-talking.gif",
        "stern": "characters/mia/stern.gif",
        "stern-talking": "characters/mia/stern-talking.gif",
    }),
    Character(name="Michael", age=50, description="Surnommé \"Le grand garçon\" il est la victime dans l'affaire, mort asphysié.", photo="characters/michael/profile.png")
]

evidences = [
    Evidence(name="Feuilles de consignes", description="Les feuilles de consignes que Michael avait donné aux élèves avant son décès", image="evidences/feuilles-de-consignes.png"),
    Evidence(name="Feuille de consigne en boule", description="L'arme du crime, une feuille de consigne en boule. De la bave de la victime a été retrouvé dessus.", image="evidences/arme-du-crime.png"),
    Evidence(name="Feuille de présence", description="La feuille de présence montre que Léna était présente au cours qui a eu lieu pendant le meurtre.", image="evidences/feuille-de-presence.png"), # Sera ajouté plus tard par la défense
    Evidence(name="Empreintes digitales", description="Les empreintes digitales de Léna ont été retrouvées sur l'arme du crime.", image="evidences/empreintes-digitales.png"), # Sera ajouté plus tard par le procureur
    Evidence(name="Rapport d'autopsie de Michael", description="Décès le 10/01, entre 14h et 16h. Cause du décès : étouffement.", image="evidences/rapport-autopsie.png"),
]

def nodes() -> list[Node]:
    nodes = [

        # INTRO - SALLE D'ATTENTE

        Node(
            id="s1-date",
            type="dialogue",
            scene=Scene(
                textType="date",
                text="16 Janvier, 16h\nTribunal fédéral\nSalle d'attente",
            ),
            nextId="s1-1",
        ),
        Node(
            id="s1-1",
            type="dialogue",
            scene=Scene(
                background=WAITING_ROOM_BG,
                character=characters[0],
                characterEmotion="normal",
                characterText="Elouan",
                textType="thought",
                text="(Respire... C'est juste un procès pour meurtre. Juste.)",
                music="musics/courtroom-lounge.mp3",
            ),
            nextId="s1-2",
        ),
        Node(
            id="s1-2",
            type="dialogue",
            scene=Scene(
                background=WAITING_ROOM_BG,
                character=characters[0],
                characterEmotion="sad",
                characterText="Léna",
                textType="dialogue",
                text="Elouan... j'ai rien à dire pour l'instant.",
            ),
            nextId="s1-3",
        ),
        Node(
            id="s1-3",
            type="dialogue",
            scene=Scene(
                background=WAITING_ROOM_BG,
                character=characters[0],
                characterEmotion="backside",
                characterText="Elouan",
                textType="dialogue",
                text="Rien ? Même pas un petit \"je suis innocente\" ? Un mini-aveu de respiration ?",
            ),
            nextId="s1-4",
        ),
        Node(
            id="s1-4",
            type="dialogue",
            scene=Scene(
                background=WAITING_ROOM_BG,
                character=characters[0],
                characterEmotion="thinking-talking",
                characterText="Léna",
                textType="dialogue",
                text="Si je parle, je vais exploser. Et je veux pas me griller.",
            ),
            nextId="s1-5",
        ),
        Node(
            id="s1-5",
            type="dialogue",
            scene=Scene(
                background=WAITING_ROOM_BG,
                character=characters[4],
                characterEmotion="normal-talking",
                characterText="Romane",
                textType="dialogue",
                text="Parfait. Alors toi, tu restes calme. Moi, je vais chercher du concret.",
            ),
            nextId="s1-6",
        ),
        Node(
            id="s1-6",
            type="dialogue",
            scene=Scene(
                background=WAITING_ROOM_BG,
                character=characters[4],
                characterEmotion="normal-talking",
                characterText="Romane",
                textType="dialogue",
                text="Je reviens avec une preuve qui claque. Ou au minimum un truc qui grince.",
            ),
            nextId="s1-7",
        ),
        Node(
            id="s1-7",
            type="dialogue",
            scene=Scene(
                background=WAITING_ROOM_BG,
                character=characters[2],
                characterEmotion="sweating",
                characterText="Elouan",
                textType="thought",
                text="(Super. Moi je stresse, elle elle fait du parkour légal.)",
            ),
            nextId="s1-8",
        ),
        Node(
            id="s1-8",
            type="dialogue",
            scene=Scene(
                background=WAITING_ROOM_BG,
                character=characters[0],
                characterEmotion="sad-talking",
                characterText="Léna",
                textType="dialogue",
                text="Je veux juste que ça s'arrête. Les consignes... c'était l'enfer.",
            ),
            nextId="s1-9",
        ),
        Node(
            id="s1-9",
            type="dialogue",
            scene=Scene(
                characterText="Elouan",
                textType="dialogue",
                text="Très bien. Je vais te sortir de là.",
                music="None",
            ),
            nextId="s2-date",
        ),

        # TRIBUNAL - OUVERTURE + TEST

        Node(
            id="s2-date",
            type="dialogue",
            scene=Scene(
                textType="date",
                text="16 Janvier, 16h12\nTribunal fédéral\nSalle d'audience n° 2",
            ),
            nextId="s2-1",
        ),
        Node(
            id="s2-1",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="normal-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="Je déclare l'audience ouverte. Affaire : Léna contre la clarté des consignes.",
                music="musics/court-begins.mp3",
            ),
            nextId="s2-2",
        ),
        Node(
            id="s2-2",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="stern-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="L'accusation est prête, Votre Honneur. Et les signatures aussi.",
            ),
            nextId="s2-3",
        ),
        Node(
            id="s2-3",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="normal-talking",
                characterText="Elouan",
                textType="dialogue",
                text="La défense est prête, Votre Honneur.",
            ),
            nextId="s2-4",
        ),
        Node(
            id="s2-4",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="thinking",
                characterText="Venceslas",
                textType="dialogue",
                text="Hum. Très bien. Avant tout...",
            ),
            nextId="s2-5",
        ),
        Node(
            id="s2-5",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="Maitre, vous suivez le dossier ? Deux questions. Simple. Comme un apéro.",
            ),
            nextId="s2-test-1",
        ),

        # Test 1 : nom de la victime

        Node(
            id="s2-test-1",
            type="choice",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="Question n°1 : Quel est le nom de la victime ?",
            ),
            options=[
                Option(text="Michael", nextId="s2-test-1_ok_1"),
                Option(text="Romane", nextId="s2-test-1_bad_1"),
                Option(text="Marie-Claire", nextId="s2-test-1_bad_1"),
            ],
        ),
        Node(
            id="s2-test-1_bad_1",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="surprised",
                characterText="Venceslas",
                textType="dialogue",
                text="... Non.",
            ),
            nextId="s2-test-1_bad_2",
        ),
        Node(
            id="s2-test-1_bad_2",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="dismayed-talking",
                characterText="Elouan",
                textType="dialogue",
                text="Pardon, Votre Honneur. J'ai eu un... bug de cerveau.",
            ),
            nextId="s2-test-1",
        ),
        Node(
            id="s2-test-1_ok_1",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="nodding-head",
                backupCharacterEmotion="normal",
                characterText="Venceslas",
                textType="dialogue",
                text="Correct.",
            ),
            nextId="s2-test-2",
        ),

        # Test 2 : cause de la mort

        Node(
            id="s2-test-2",
            type="choice",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="Question n°2 : Comment est morte la victime ?",
            ),
            options=[
                Option(text="Asphyxiée", nextId="s2-test-2_ok_1"),
                Option(text="Assommée", nextId="s2-test-2_bad_1"),
                Option(text="Poignardée", nextId="s2-test-2_bad_1"),
            ],
        ),
        Node(
            id="s2-test-2_bad_1",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="shaking-head",
                backupCharacterEmotion="stern",
                characterText="Venceslas",
                textType="dialogue",
                text="Incorrect. Ne me dites pas que vous plaidez au hasard.",
            ),
            nextId="s2-test-2_bad_2",
        ),
        Node(
            id="s2-test-2_bad_2",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="thinking",
                characterText="Elouan",
                textType="thought",
                text="(Ok. Calme. Dossier. Cerveau. Fonctionne.)",
            ),
            nextId="s2-test-2",
        ),
        Node(
            id="s2-test-2_ok_1",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="nodding-head",
                backupCharacterEmotion="normal",
                characterText="Venceslas",
                textType="dialogue",
                text="Correct. On peut poursuivre.",
            ),
            nextId="s2-6",
        ),

        # PRESENTATION DES PREUVES DE BASE (consignes + arme)

        Node(
            id="s2-6",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="normal-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="Votre Honneur, l'accusée a craqué. Et elle a agi.",
            ),
            nextId="s2-7",
        ),
        Node(
            id="s2-7",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="stern-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="La victime, Michael, a été étouffée avec une feuille de consigne froissée.",
                extraElements=[{"evidence": evidences[1]}],
            ),
            nextId="s2-8",
        ),
        Node(
            id="s2-8",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="La cour accepte cette pièce.",
            ),
            nextId="s2-9",
        ),
        Node(
            id="s2-9",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="normal",
                characterText="",
                textType="thought",
                text="Feuille de consigne en boule ajoutée au dossier de l'affaire.",
                extraElements=[{"add_evidence": evidences[1]}],
            ),
            nextId="s2-10",
        ),
        Node(
            id="s2-10",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="no-finger-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="Et voici les consignes originales. Le mobile est écrit dessus en filigrane : \"bon courage\".",
                extraElements=[{"evidence": evidences[0]}],
            ),
            nextId="s2-11",
        ),
        Node(
            id="s2-11",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="thinking",
                characterText="Venceslas",
                textType="dialogue",
                text="Hum... \"Droit à la déconnexion\"... Je vois.",
            ),
            nextId="s2-12",
        ),
        Node(
            id="s2-12",
            type="dialogue",
            scene=Scene(
                background=ASSISTANT_SIDE_BG,
                character=characters[4],
                characterEmotion="normal",
                characterText="Romane",
                textType="thought",
                text="(Je suis pas encore revenue... Patience, Elouan.)",
            ),
            nextId="s2-13",
        ),

        # LA DEFENSE SUBIT + ARRIVEE DE ROMANE AVEC UNE PREUVE

        Node(
            id="s2-13",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="thinking-talking",
                characterText="Elouan",
                textType="dialogue",
                text="Votre Honneur, des consignes floues, ça ne prouve pas un meurtre.",
            ),
            nextId="s2-14",
        ),
        Node(
            id="s2-14",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="overhead-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="Oh ? Pourtant, on a des témoins : \"Elle avait la feuille en main\".",
            ),
            nextId="s2-15",
        ),
        Node(
            id="s2-15",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="La défense a-t-elle quelque chose de solide ?",
            ),
            nextId="s2-16",
        ),
        Node(
            id="s2-16",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="dismayed",
                characterText="Elouan",
                textType="thought",
                text="(Solide ? Là, tout de suite ? J'ai une angoisse bien compacte, ça compte ?)",
            ),
            nextId="s2-17",
        ),
        Node(
            id="s2-17",
            type="dialogue",
            scene=Scene(
                background=ASSISTANT_SIDE_BG,
                character=characters[4],
                characterEmotion="grinning-talking",
                characterText="Romane",
                textType="dialogue",
                text="J'arrive avec du solide.",
            ),
            nextId="s2-18",
        ),
        Node(
            id="s2-18",
            type="dialogue",
            scene=Scene(
                background=ASSISTANT_SIDE_BG,
                character=characters[4],
                characterEmotion="stern-talking",
                characterText="Romane",
                textType="dialogue",
                text="Elouan, présente ça : la feuille de présence du cours, à l'heure du meurtre.",
                extraElements=[{"evidence": evidences[2]}],
            ),
            nextId="s2-19",
        ),
        Node(
            id="s2-19",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="determined-talking",
                characterText="Elouan",
                textType="dialogue",
                text="Votre Honneur ! La défense présente la feuille de présence.",
                extraElements=[{"evidence": evidences[2]}],
            ),
            nextId="s2-20",
        ),
        Node(
            id="s2-20",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="Je vois... La cour l'accepte en tant que pièce à conviction.",
            ),
            nextId="s2-21",
        ),
        Node(
            id="s2-21",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="normal",
                textType="thought",
                text="Feuille de présence ajoutée au dossier de l'affaire.",
                extraElements=[{"add_evidence": evidences[2]}],
            ),
            nextId="s2-22",
        ),

        # CONTRE-ATTAQUE : "FAUSSE SIGNATURE" + EMPREINTES DIGITALES AJOUTEES

        Node(
            id="s2-22",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="stern",
                characterText="Marie-Claire",
                textType="dialogue",
                text="... Intéressant.",
            ),
            nextId="s2-23",
        ),
        Node(
            id="s2-23",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="stern-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="Mais je scrute les signatures. C'est mon sport. Et celle-ci... est fausse.",
            ),
            nextId="s2-24",
        ),
        Node(
            id="s2-24",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="shocked",
                backupCharacterEmotion="dismayed",
                characterText="Elouan",
                textType="thought",
                text="(Quoi ?! Elle vient de faire un examen graphologique à l'oeil nu ?!)",
            ),
            nextId="s2-25",
        ),
        Node(
            id="s2-25",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="no-finger-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="Et pour enfoncer le clou... voici les empreintes digitales sur l'arme.",
                extraElements=[{"evidence": evidences[3]}],
            ),
            nextId="s2-26",
        ),
        Node(
            id="s2-26",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="surprised-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="Des empreintes ? Sur l'arme du crime ?!",
            ),
            nextId="s2-27",
        ),
        Node(
            id="s2-27",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="La cour accepte ces empreintes en tant que pièce à conviction.",
            ),
            nextId="s2-28",
        ),
        Node(
            id="s2-28",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="normal",
                textType="thought",
                text="Empreintes digitales ajoutées au dossier de l'affaire.",
                extraElements=[{"add_evidence": evidences[3]}],
            ),
            nextId="s2-29",
        ),
        Node(
            id="s2-29",
            type="dialogue",
            scene=Scene(
                background=WITNESS_SIDE_BG,
                character=characters[0],
                characterEmotion="surprised-talking",
                characterText="Léna",
                textType="dialogue",
                text="Mais... j'ai touché cette feuille, oui ! C'était un cours !",
            ),
            nextId="s2-30",
        ),
        Node(
            id="s2-30",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="whipping",
                backupCharacterEmotion="overhead-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="Touché, donc. Et maintenant : coupable, donc.",
            ),
            nextId="s2-31",
        ),

        # MINI SEQUENCE "PRESSION" + Elouan SE RESSAISIT

        Node(
            id="s2-31",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="thinking",
                characterText="Elouan",
                textType="thought",
                text="(Ok. Empreintes = elle a tenu l'objet. Pas forcément qu'elle a tué.)",
            ),
            nextId="s2-32",
        ),
        Node(
            id="s2-32",
            type="dialogue",
            scene=Scene(
                background=ASSISTANT_SIDE_BG,
                character=characters[4],
                characterEmotion="stern-talking",
                characterText="Romane",
                textType="thought",
                text="Reste sur un truc simple : le mobile. Et le contexte.",
            ),
            nextId="s2-33",
        ),
        Node(
            id="s2-33",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="Bien... Nous avons une arme, et des empreintes. Le mobile, maintenant.",
            ),
            nextId="s2-34",
        ),
        Node(
            id="s2-34",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="L'accusation avance un énervement lié à des consignes floues.",
            ),
            nextId="s2-35",
        ),
        Node(
            id="s2-35",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="stern-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="Exactement. \"Droit à la déconnexion\" bafoué, rage, passage à l'acte.",
            ),
            nextId="s2-36",
        ),
        Node(
            id="s2-36",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="determined-talking",
                characterText="Elouan",
                textType="dialogue",
                text="Votre Honneur, être à bout n'est pas une preuve de meurtre.",
            ),
            nextId="s2-37",
        ),
        Node(
            id="s2-37",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="sweating-talking",
                characterText="Marie-Claire",
                textType="dialogue",
                text="Oh ? Et vous comptez plaider quoi ? \"C'est la faute des consignes\" ?",
            ),
            nextId="s2-38",
        ),
        Node(
            id="s2-38",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="pointing-talking",
                characterText="Elouan",
                textType="dialogue",
                text="Je compte plaider la logique. Et la nuance.",
            ),
            nextId="s2-39",
        ),

        # DERNIERE QUESTION (CHOICE) : "Le mobile de Léna est"

        Node(
            id="s2-39",
            type="choice",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="Dernière question : Le mobile de Léna est :",
            ),
            options=[
                Option(text="Inexistant", nextId="s2-39_bad_1"),
                Option(text="Purement jaloux", nextId="s2-39_bad_1"),
                Option(text="Justifié (Cheh)", nextId="s2-39_ok_1"),
            ],
        ),
        Node(
            id="s2-39_bad_1",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="shaking-head",
                backupCharacterEmotion="stern",
                characterText="Venceslas",
                textType="dialogue",
                text="Non. Vous passez à côté du contexte. Reprenez.",
            ),
            nextId="s2-39",
        ),
        Node(
            id="s2-39_ok_1",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="surprised-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="... \"Justifié\" ? Voilà qui est... audacieux.",
            ),
            nextId="s2-40",
        ),
        Node(
            id="s2-40",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="damaged",
                characterText="Marie-Claire",
                textType="dialogue",
                text="Votre Honneur ! On ne peut pas écrire \"cheh\" dans un tribunal !",
            ),
            nextId="s2-41",
        ),
        Node(
            id="s2-41",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="confident-talking",
                characterText="Elouan",
                textType="dialogue",
                text="Je ne justifie pas un meurtre. Je dis que le mobile supposé est compréhensible...",
            ),
            nextId="s2-42",
        ),
        Node(
            id="s2-42",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="determined-talking",
                characterText="Elouan",
                textType="dialogue",
                text="... et que ça ne suffit pas à condamner Léna sans une preuve directe de l'acte.",
            ),
            nextId="s2-43",
        ),
        Node(
            id="s2-43",
            type="dialogue",
            scene=Scene(
                background=ASSISTANT_SIDE_BG,
                character=characters[4],
                characterEmotion="stern-talking",
                characterText="Romane",
                textType="dialogue",
                text="Bien joué. Maintenant, on va leur faire admettre une chose : toucher, ce n'est pas tuer.",
            ),
            nextId="s2-44",
        ),
        Node(
            id="s2-44",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="thinking",
                characterText="Venceslas",
                textType="dialogue",
                text="Hum... L'audience va se poursuivre. Mais je garde l'apéro en ligne de mire.",
            ),
            nextId="s2-45",
        ),
        Node(
            id="s2-45",
            type="dialogue",
            scene=Scene(
                background=JUDGE_SIDE_BG,
                character=characters[3],
                characterEmotion="stern-talking",
                characterText="Venceslas",
                textType="dialogue",
                text="Pour l'instant, je demande à l'accusation de clarifier : quand exactement l'arme a été manipulée.",
            ),
            nextId="s2-46",
        ),
        Node(
            id="s2-46",
            type="dialogue",
            scene=Scene(
                background=PROSECUTOR_SIDE_BG,
                character=characters[1],
                characterEmotion="sweating",
                characterText="Elouan",
                textType="thought",
                text="(Tch... Il commence à douter. Je dois verrouiller avec les signatures.)",
            ),
            nextId="s2-47",
        ),
        Node(
            id="s2-47",
            type="dialogue",
            scene=Scene(
                background=WITNESS_SIDE_BG,
                character=characters[0],
                characterEmotion="sad",
                characterText="Elouan",
                textType="thought",
                text="(Elouan... tiens bon. Moi aussi.)",
            ),
            nextId="s2-48",
        ),
        Node(
            id="s2-48",
            type="dialogue",
            scene=Scene(
                background=DEFENSE_SIDE_BG,
                character=characters[2],
                characterEmotion="determined",
                characterText="Elouan",
                textType="thought",
                text="(Ok. Prochaine étape : démonter leur certitude. Une feuille à la fois.)",
            ),
            nextId="s2-end",
        ),
        Node(
            id="s2-end",
            type="dialogue",
            scene=Scene(
                characterText="",
                textType="thought",
                text="Fin de la démo. (A suivre...)",
                music="None",
            ),
            nextId=None,
        ),
    ]

    return {n.id: n for n in nodes}

def court_record() -> CourtRecord:
    choosed_evidences = [
        evidences[0],
        evidences[4],
    ]
    choosed_profiles = [
        characters[4],
        characters[5],
        characters[0],
        characters[1],
        characters[3],
    ]
    return CourtRecord(evidences=choosed_evidences, profils=choosed_profiles)